#!/bin/sh

mount -n -t proc proc /proc
mount -n -t sysfs sysfs /sys
mount -n -t tmpfs tmpfs /dev/mapper
mount -n -t tmpfs tmpfs /dev/data
CMDLINE=`cat /proc/cmdline`

vgchange -ay
echo > /sys/power/tuxonice/do_resume
mount -n -r -t ext4 /dev/mapper/data-root /newroot || lvm

cd /newroot
umount /dev/mapper
umount /dev/data
umount /sys
umount /proc
exec chroot . /bin/sh -c "exec /sbin/init ${CMDLIND}" <dev/console >dev/console 2>&1

