#!/bin/bash

file="/tmp/packagedModules"

cd /usr/src/linux || ( echo "No kernel directory"; exit 1 )
make -j2 || ( echo "Make failed" ; exit 1 )
make modules -j2 || ( echo "Make modules failed" ; exit 1 )
make modules_install -j2 || ( echo "Make modules install failed" ; exit 1 )
qfile -q -C /lib/modules > $file
if [ -s $file ] ; then
	emerge -q1 `cat $file` || exit 1
fi
make install -j2 || ( echo "Make install failed" ; exit 1 )
