#!/bin/bash

file="/var/www/files/localhost/`hostname`_updates.txt"
dpfile="/var/www/files/localhost/`hostname`_depclean.txt"
tty -s
TTYTEST=$?
( \
	( \
		( \
			emerge -uqDN -j2 @world @system --keep-going && \
			rm -f $file ) || \
		/etc/portage/postsync.d/50-write-new-updates ) && \
	emerge --depclean -q 2>&1 | tee $dpfile && \
	emerge -q @preserved-rebuild \
)
revdep-rebuild -q -i
if [ $TTYTEST -eq 0 ]; then
	etc-update 
fi
