#!/bin/bash

cd /usr/src/linux || ( echo "No kernel directory"; exit 1 )
make -j2 || ( echo "Make failed" ; exit 1 )
make modules -j2 || ( echo "Make modules failed" ; exit 1 )
make modules_install -j2 || ( echo "Make modules install failed" ; exit 1 )
emerge -q1 /lib/modules || exit 1
make install -j2 || ( echo "Make install failed" ; exit 1 )
[ -x /usr/sbin/dracut ] && /usr/sbin/dracut -H -f --lzma /boot/dracut.initrd.cpio.lzma $(head /boot/config -n3 | tail -n1 | cut -d ' ' -f 3)
