#!/bin/bash

unset ABI ABI_X86
eval $(emerge --info -v | grep '^UPDATESTATEDIR="[^"]*"$')
updates="${UPDATESTATEDIR:-/tmp}/`hostname`_updates.txt"

tmp="/tmp/$$.updates"
emerge -uDNpvq --with-bdeps=y @world @system > ${tmp}
mv ${tmp} ${updates}

