#!/bin/bash

unset ABI ABI_X86
UPDATESTATEDIR=$(portageq envvar UPDATESTATEDIR)
updates="${UPDATESTATEDIR:-/tmp}/`hostname`_updates.txt"

tmp="/tmp/$$.updates"
emerge -uDNpvq --with-bdeps=y @world @system > ${tmp}
mv ${tmp} ${updates}

