# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI="7"

DIST_AUTHOR="GTERMARS"
DIST_VERSION="${PV}"


inherit perl-module

DESCRIPTION="XS based CSS minifier"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64 x86"
IUSE=""

DEPEND="
	dev-lang/perl
	dev-perl/Module-Build
"

